root: true
extends:
  - "plugin:vue/vue3-recommended"
  - "eslint:recommended"
  - "plugin:@typescript-eslint/recommended"
  - "prettier"
plugins:
  - "@typescript-eslint"
parser: "vue-eslint-parser"
parserOptions:
  parser: "@typescript-eslint/parser"
  sourceType: "module"
rules:
  "no-unused-vars": "error"
  "vue/multi-word-component-names": "off"
  "semi": ["warn", "never"]
